"""Epistemic Invariants implementation (Invariant I3, I4, I8, I10)."""

import time

def get_authority_for_role(origin: str, role: str) -> float:
    """Invariant I3 & I4: No LLM token generated by any model (Assistant, Subconscious, Superconscious,
    Conscience) can increase epistemic authority without physical tool proof.
    Assistant/LLM authority is always 0.0 (anti-self-poisoning).
    Direct user authority is 1.0. Runtime tool verified is 1.0.
    """
    if role == "assistant" or origin in (
        "assistant", "subconscious", "superconscious", "nadswiadomosc",
        "podswiadomosc", "sumienie", "llm", "synthetic"
    ):
        return 0.0
    if origin == "direct_user":
        return 1.0
    if origin in ("harness_event", "synthetic_demo"):
        return 0.2
    if role == "user" and origin != "external":
        return 0.9 if origin != "direct_user" else 1.0
    if origin in ("runtime_tool_verified", "tool_verified"):
        return 1.0
    if origin in ("tool", "tool_observation"):
        return 0.9
    if origin == "system" and role == "system":
        return 1.0
    if origin == "system":
        return 0.5
    if origin == "external":
        return 0.2
    return 0.0

def cap_derived_authority(root_authority: float, claimed_authority: float) -> float:
    """Invariant I4: Derived authority can never exceed root authority (No authority laundering)."""
    return min(root_authority, claimed_authority)


from enum import Enum
from typing import Any, Dict, List, Optional, Tuple


class EpistemicRejectionType(str, Enum):
    VERIFIED = "VERIFIED"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    CONTRADICTED = "CONTRADICTED"
    FORMAT_MISMATCH = "FORMAT_MISMATCH"
    INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    UNDECIDABLE = "UNDECIDABLE"


def validate_retry_attempt(
    prior_attempts: List[Dict[str, Any]],
    current_attempt: Dict[str, Any]
) -> Tuple[bool, Optional[str]]:
    """Invariant I11: No Epistemically Equivalent Retry.

    A retry attempt is allowed iff:
    - It introduces new evidence (different evidence hash / new tool result),
    - It invokes a different tool or different parameters/strategy,
    - Or it addresses a format mismatch without repeating research.

    Identical attempts with identical tools, queries, or epistemic states are strictly forbidden.
    """
    curr_tool = current_attempt.get("tool")
    curr_input = current_attempt.get("input") or current_attempt.get("query") or current_attempt.get("code")
    curr_evidence_hash = current_attempt.get("evidence_hash")

    for prior in prior_attempts:
        p_tool = prior.get("tool")
        p_input = prior.get("input") or prior.get("query") or prior.get("code")
        p_evidence_hash = prior.get("evidence_hash")
        p_status = prior.get("status")

        # If previous attempt was rejected and current attempt is identical in tool, input, and evidence
        if (
            p_tool == curr_tool
            and p_input == curr_input
            and p_evidence_hash == curr_evidence_hash
            and p_status in (
                EpistemicRejectionType.MISSING_EVIDENCE.value,
                EpistemicRejectionType.INVARIANT_VIOLATION.value,
                EpistemicRejectionType.CONTRADICTED.value,
            )
        ):
            return (
                False,
                f"Invariant I11 Violation: Epistemically equivalent retry forbidden for tool '{curr_tool}' "
                f"without new evidence, alternative tool, or modified strategy."
            )

    return True, None


from pathlib import Path
import re
from cognitive.contracts import GateDecision, RepairTicket, EvidenceObject


def evaluate_conscience_gate(
    candidate_answer: Optional[str],
    tool_events: List[Dict[str, Any]],
    question: str = ""
) -> GateDecision:
    """Conscience Hard Gate & Normalizer (Invariant I4 & Option D).

    Strict separation of powers:
    1. Zero Content Generation: Conscience never writes, invents, or alters answer payload.
    2. Hard Deterministic Gate: Checks tool exit codes, error traces, exceptions.
       Unhandled failures (exit != 0, unhandled Exception, empty results) block VERIFIED status.
    3. Deterministic Normalizer: Only unit conversion requested in prompt or scalar extraction.
    """
    if not candidate_answer or candidate_answer.strip() in ("", "None"):
        ticket = RepairTicket(
            claim_id="root",
            error_type=EpistemicRejectionType.MISSING_EVIDENCE,
            required_action="Worker must propose a grounded candidate answer",
            required_proof={"type": "candidate_answer", "non_empty": True}
        )
        return GateDecision(
            decision="REJECTED",
            candidate_answer=str(candidate_answer),
            reason="NO_CANDIDATE_ANSWER",
            repair_ticket=ticket
        )

    raw_str = str(candidate_answer).strip()

    # Clean candidate scalar from common wrappers
    m = re.search(r'FINAL ANSWER:\s*([^\n]+)', raw_str, re.IGNORECASE)
    if m:
        raw_str = m.group(1).strip().strip('"`*')
    else:
        lines = [l.strip() for l in raw_str.splitlines() if l.strip() and not l.startswith("```")]
        raw_str = lines[-1] if lines else raw_str
        raw_str = re.sub(r'^(FINAL ANSWER|Answer|The answer is):\s*', '', raw_str, flags=re.IGNORECASE).strip('"`*')

    # 1. HARD GATE: Did candidate declare inability or technical limitation?
    if any(phrase in raw_str.lower() for phrase in [
        "cannot answer", "unable to", "not found", "technical limitations", "error:"
    ]):
        ticket = RepairTicket(
            claim_id="root",
            error_type=EpistemicRejectionType.MISSING_EVIDENCE,
            required_action="Acquire missing evidence via tools rather than declaring inability",
            required_proof={"type": "tool_execution", "status": "SUCCESS"}
        )
        return GateDecision(
            decision="REJECTED",
            candidate_answer=raw_str,
            reason="WORKER_CONFESSED_INABILITY",
            repair_ticket=ticket
        )

    # 2. HARD GATE: If tool execution failed completely with error
    failed_tools = [
        t for t in tool_events 
        if t.get("status") == "ERROR" or "error" in str(t.get("output", "")).lower() or "exception" in str(t.get("output", "")).lower()
    ]
    if failed_tools and len(failed_tools) == len(tool_events):
        ticket = RepairTicket(
            claim_id="root",
            error_type=EpistemicRejectionType.INVARIANT_VIOLATION,
            required_action="Fix tool code or query; all executions failed",
            required_proof={"failed_tools": [t.get("tool") for t in failed_tools]}
        )
        return GateDecision(
            decision="REJECTED",
            candidate_answer=raw_str,
            reason="EXECUTION_FAILED",
            repair_ticket=ticket
        )

    # 3. DETERMINISTIC NORMALIZATION (Units and numbers)
    clean_ans = raw_str.rstrip('.')

    # Unit normalization (e.g. 17000 hours -> 17 thousand hours)
    if re.search(r'how many thousand', question, re.IGNORECASE) and clean_ans.isdigit() and len(clean_ans) >= 4:
        val_num = int(clean_ans)
        if val_num % 1000 == 0:
            clean_ans = str(val_num // 1000)

    # High-precision decimals preservation
    if not re.search(r'round', question, re.IGNORECASE):
        high_prec = re.search(r'\b\d+\.\d{3,}\b', raw_str)
        if high_prec:
            clean_ans = high_prec.group(0)

    return GateDecision(
        decision="VERIFIED",
        candidate_answer=raw_str,
        verified_answer=clean_ans,
        reason="DETERMINISTIC_GATE_PASSED"
    )


def resolve_required_modalities(question: str, attached_files: Optional[List[str]] = None) -> Dict[str, Any]:
    """Resolve required modalities and map required tools before dispatching workers."""
    attached_files = attached_files or []
    modalities = set(["text"])
    tools = set(["web_search", "python_exec"])

    for f in attached_files:
        ext = Path(f).suffix.lower()
        if ext in (".xlsx", ".xls"):
            modalities.add("spreadsheet")
            tools.add("file_read")
            tools.add("python_exec")
        elif ext == ".docx":
            modalities.add("document")
            tools.add("file_read")
        elif ext == ".pptx":
            modalities.add("presentation")
            tools.add("file_read")
        elif ext == ".pdf":
            modalities.add("pdf")
            tools.add("file_read")
        elif ext in (".mp3", ".wav", ".m4a"):
            modalities.add("audio")
            tools.add("file_read")
        elif ext in (".png", ".jpg", ".jpeg", ".webp"):
            modalities.add("vision")
            tools.add("file_read")
        elif ext in (".zip", ".tar", ".gz", ".tgz"):
            modalities.add("archive")
            tools.add("file_read")
            tools.add("python_exec")
        elif ext in (".mp4", ".webm", ".mkv", ".mov"):
            modalities.add("video")
            tools.add("video_inspect")
        elif ext == ".py":
            modalities.add("code")
            tools.add("file_read")
            tools.add("python_exec")

    if "video" in question.lower() or "youtube.com" in question.lower() or "youtu.be" in question.lower():
        modalities.add("video")
        tools.add("video_inspect")
        tools.add("web_search")
        tools.add("web_extract")

    return {
        "required_modalities": sorted(list(modalities)),
        "recommended_tools": sorted(list(tools))
    }


import hashlib
import json
import sqlite3


def record_experience_event(
    conn: sqlite3.Connection,
    task_signature: str,
    intent: str,
    modalities: List[str],
    strategy: str,
    tool_sequence: List[str],
    evidence_refs: List[str],
    outcome: str = "VERIFIED"
) -> str:
    """Store a verified trajectory in the local experience buffer for replay/priors."""
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    exp_id = f"exp_{hashlib.sha256(f'{task_signature}_{now}'.encode()).hexdigest()[:16]}"
    payload = f"{task_signature}|{strategy}|{tool_sequence}|{outcome}"
    exp_hash = hashlib.sha256(payload.encode("utf-8")).hexdigest()

    conn.execute("""
        INSERT OR REPLACE INTO experience_events (
            experience_id, task_signature, intent, modalities, strategy,
            tool_sequence, evidence_refs, outcome, experience_hash, created_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        exp_id, task_signature, intent, json.dumps(modalities), strategy,
        json.dumps(tool_sequence), json.dumps(evidence_refs), outcome, exp_hash, now
    ))
    conn.commit()
    return exp_id


def retrieve_experience_priors(
    conn: sqlite3.Connection,
    intent: str,
    modalities: Optional[List[str]] = None,
    limit: int = 3
) -> List[Dict[str, Any]]:
    """Retrieve proven strategies from previous successful runs for similar task signatures."""
    try:
        cursor = conn.execute("""
            SELECT task_signature, intent, modalities, strategy, tool_sequence, outcome
            FROM experience_events
            WHERE outcome = 'VERIFIED'
            ORDER BY created_at DESC
            LIMIT 50
        """)
        rows = cursor.fetchall()
        matches = []
        intent_words = set(intent.lower().split())
        for row in rows:
            r_sig, r_intent, r_mods, r_strat, r_tools, r_out = row
            r_words = set(r_intent.lower().split())
            overlap = len(intent_words & r_words)
            if overlap > 0 or (modalities and any(m in (r_mods or "") for m in modalities)):
                matches.append({
                    "task_signature": r_sig,
                    "intent": r_intent,
                    "strategy": r_strat,
                    "tools": json.loads(r_tools) if r_tools.startswith("[") else [],
                    "relevance": overlap
                })
        matches.sort(key=lambda x: x["relevance"], reverse=True)
        return matches[:limit]
    except Exception:
        return []


