"""Improvement ledger ("mods") for the JIT/JEV harness.

mods.json (state dir) is the source of truth; jitjevmods.md is regenerated from it after every change so the
file never accumulates duplicate lines. A mod is keyed by a stable id; repeated detections bump its counter.
Set `"status": "done"` or `"wontfix"` in mods.json by hand (or via set_status) - regeneration keeps it.
"""
from __future__ import annotations

import json
import os
import tempfile
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from config import STATE_DIR

AUDIT_DIR = STATE_DIR / "audits"
MODS_JSON = AUDIT_DIR / "mods.json"
_DEFAULT_REPO = Path.home() / ".hermes" / "research" / "hermes-jit-context-os-v0.1"
MODS_MD = Path(os.environ.get("JIT_MODS_PATH") or (_DEFAULT_REPO / "jitjevmods.md" if _DEFAULT_REPO.exists() else AUDIT_DIR / "jitjevmods.md"))
MAX_EXAMPLES = 3
SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2}


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, path)


def load_mods() -> Dict[str, Dict[str, Any]]:
    try:
        return json.loads(MODS_JSON.read_text(encoding="utf-8"))
    except (FileNotFoundError, ValueError):
        return {}


def record_mods(findings: List[Dict[str, Any]], source: Dict[str, str]) -> None:
    """Merge findings into the ledger. Each finding: key, title, component, proposal, severity, evidence."""
    if not findings:
        return
    mods, now = load_mods(), time.time()
    for f in findings:
        m = mods.setdefault(f["key"], {
            "key": f["key"], "title": f["title"], "component": f["component"], "proposal": f["proposal"],
            "severity": f["severity"], "status": "open", "count": 0, "first_seen": now, "examples": [],
        })
        m.update(title=f["title"], component=f["component"], proposal=f["proposal"])
        if SEVERITY_ORDER[f["severity"]] < SEVERITY_ORDER.get(m["severity"], 2):
            m["severity"] = f["severity"]
        m["count"] += 1
        m["last_seen"] = now
        m["examples"] = ([{**source, "evidence": f["evidence"][:240], "ts": now}] + m["examples"])[:MAX_EXAMPLES]
    _atomic_write(MODS_JSON, json.dumps(mods, ensure_ascii=False, indent=2))
    render_markdown(mods)


def set_status(key: str, status: str) -> bool:
    mods = load_mods()
    if key not in mods:
        return False
    mods[key]["status"] = status
    _atomic_write(MODS_JSON, json.dumps(mods, ensure_ascii=False, indent=2))
    render_markdown(mods)
    return True


def ranked(mods: Optional[Dict[str, Dict[str, Any]]] = None) -> List[Dict[str, Any]]:
    mods = load_mods() if mods is None else mods
    return sorted(mods.values(), key=lambda m: (m.get("status") != "open", SEVERITY_ORDER.get(m["severity"], 2), -m["count"]))


def render_markdown(mods: Dict[str, Dict[str, Any]]) -> None:
    fmt = lambda ts: time.strftime("%Y-%m-%d %H:%M", time.localtime(ts)) if ts else "-"  # noqa: E731
    rows = ranked(mods)
    open_n = sum(1 for m in rows if m.get("status") == "open")
    out = [
        "# JIT / JEV harness mods",
        "",
        "Improvement backlog generated by the per-turn autochecker (`telemetry/turn_audit.py`).",
        "Every Hermes turn is checked: project goal vs user prompt vs spec vs capsule vs output, plus harness efficiency.",
        f"Source of truth: `{MODS_JSON}` (edit `status` there). Live view: http://127.0.0.1:8766/live",
        "",
        f"Updated {fmt(time.time())} · {open_n} open · {len(rows) - open_n} closed",
        "",
        "| # | Severity | Status | Seen | Component | Mod |",
        "|---|---|---|---|---|---|",
    ]
    for i, m in enumerate(rows, 1):
        out.append(f"| {i} | {m['severity']} | {m.get('status', 'open')} | {m['count']}x | {m['component']} | [{m['title']}](#{m['key']}) |")
    for m in rows:
        out += ["", f"## {m['key']}", "", f"**{m['title']}** · {m['severity']} · {m.get('status', 'open')} · seen {m['count']}x "
                f"(first {fmt(m.get('first_seen'))}, last {fmt(m.get('last_seen'))})", "",
                f"- Component: {m['component']}", f"- Proposal: {m['proposal']}"]
        for ex in m.get("examples", []):
            where = " · ".join(str(ex[k]) for k in ("session", "turn", "run") if ex.get(k))
            out.append(f"- Evidence ({where}): {ex.get('evidence', '')}")
    _atomic_write(MODS_MD, "\n".join(out) + "\n")
