"""Improvement ledger ("mods") for the JIT/JEV harness in Agent Zero.

mods.json (state/data dir) is the source of truth; jitjevmods.md is regenerated from it after every change
so the file never accumulates duplicate lines. A mod is keyed by a stable id; repeated detections bump its counter.
Set `"status": "done"` or `"wontfix"` in mods.json by hand (or via set_status) - regeneration keeps it.
Self-contained Agent Zero port.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
import tempfile
import time
from typing import Any, Dict, List, Optional

_HERE = Path(__file__).resolve().parent
_PLUGIN_DIR = _HERE.parent
_DATA_DIR = Path(os.environ.get("JIT_CONTEXT_DATA_DIR") or (_PLUGIN_DIR / "data"))
_AUDIT_DIR_ENV = os.environ.get("JIT_AUDIT_DIR")

AUDIT_DIR = Path(_AUDIT_DIR_ENV) if _AUDIT_DIR_ENV else (_DATA_DIR / "audits")
MODS_JSON = AUDIT_DIR / "mods.json"
MODS_MD = Path(os.environ.get("JIT_MODS_PATH") or (AUDIT_DIR / "jitjevmods.md"))

MAX_EXAMPLES = 3
SEVERITY_ORDER = {"high": 0, "medium": 1, "low": 2}


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, path)


def load_mods(path: Optional[Path] = None) -> Dict[str, Dict[str, Any]]:
    target = path or MODS_JSON
    try:
        return json.loads(target.read_text(encoding="utf-8"))
    except (FileNotFoundError, ValueError, OSError):
        return {}


def record_mods(
    findings: List[Dict[str, Any]],
    source: Dict[str, str],
    mods_json: Optional[Path] = None,
    mods_md: Optional[Path] = None,
) -> None:
    """Merge findings into the ledger. Each finding: key, title, component, proposal, severity, evidence."""
    if not findings:
        return
    json_path = mods_json or MODS_JSON
    md_path = mods_md or MODS_MD
    mods, now = load_mods(json_path), time.time()
    for f in findings:
        key = str(f.get("key", "unknown"))
        m = mods.setdefault(
            key,
            {
                "key": key,
                "title": f.get("title", key),
                "component": f.get("component", "unknown"),
                "proposal": f.get("proposal", ""),
                "severity": f.get("severity", "medium"),
                "status": "open",
                "count": 0,
                "first_seen": now,
                "examples": [],
            },
        )
        m.update(
            title=f.get("title", m.get("title", key)),
            component=f.get("component", m.get("component", "unknown")),
            proposal=f.get("proposal", m.get("proposal", "")),
        )
        f_sev = f.get("severity", "medium")
        if SEVERITY_ORDER.get(f_sev, 2) < SEVERITY_ORDER.get(m.get("severity", "low"), 2):
            m["severity"] = f_sev
        m["count"] = int(m.get("count", 0)) + 1
        m["last_seen"] = now
        evidence = str(f.get("evidence", ""))[:240]
        m["examples"] = ([{**source, "evidence": evidence, "ts": now}] + m.get("examples", []))[:MAX_EXAMPLES]

    _atomic_write(json_path, json.dumps(mods, ensure_ascii=False, indent=2))
    render_markdown(mods, md_path=md_path, json_path=json_path)


def set_status(
    key: str,
    status: str,
    mods_json: Optional[Path] = None,
    mods_md: Optional[Path] = None,
) -> bool:
    json_path = mods_json or MODS_JSON
    md_path = mods_md or MODS_MD
    mods = load_mods(json_path)
    if key not in mods:
        return False
    mods[key]["status"] = status
    _atomic_write(json_path, json.dumps(mods, ensure_ascii=False, indent=2))
    render_markdown(mods, md_path=md_path, json_path=json_path)
    return True


def ranked(
    mods: Optional[Dict[str, Dict[str, Any]]] = None,
    json_path: Optional[Path] = None,
) -> List[Dict[str, Any]]:
    mods = load_mods(json_path) if mods is None else mods
    return sorted(
        mods.values(),
        key=lambda m: (
            m.get("status") != "open",
            SEVERITY_ORDER.get(m.get("severity", "low"), 2),
            -int(m.get("count", 0)),
        ),
    )


def render_markdown(
    mods: Dict[str, Dict[str, Any]],
    md_path: Optional[Path] = None,
    json_path: Optional[Path] = None,
) -> None:
    target_md = md_path or MODS_MD
    target_json = json_path or MODS_JSON
    fmt = lambda ts: time.strftime("%Y-%m-%d %H:%M", time.localtime(ts)) if ts else "-"  # noqa: E731
    rows = ranked(mods, json_path=target_json)
    open_n = sum(1 for m in rows if m.get("status") == "open")
    out = [
        "# JIT / JEV harness mods",
        "",
        "Improvement backlog generated by the per-turn autochecker.",
        "Every turn is checked: project goal vs user prompt vs spec vs capsule vs output, plus harness efficiency.",
        f"Source of truth: `{target_json}` (edit `status` there).",
        "",
        f"Updated {fmt(time.time())} · {open_n} open · {len(rows) - open_n} closed",
        "",
        "| # | Severity | Status | Seen | Component | Mod |",
        "|---|---|---|---|---|---|",
    ]
    for i, m in enumerate(rows, 1):
        out.append(
            f"| {i} | {m.get('severity', 'low')} | {m.get('status', 'open')} | {m.get('count', 0)}x | {m.get('component', '')} | [{m.get('title', m.get('key'))}](#{m.get('key')}) |"
        )
    for m in rows:
        out += [
            "",
            f"## {m.get('key')}",
            "",
            f"**{m.get('title')}** · {m.get('severity')} · {m.get('status', 'open')} · seen {m.get('count')}x "
            f"(first {fmt(m.get('first_seen'))}, last {fmt(m.get('last_seen'))})",
            "",
            f"- Component: {m.get('component')}",
            f"- Proposal: {m.get('proposal')}",
        ]
        for ex in m.get("examples", []):
            where = " · ".join(str(ex[k]) for k in ("session", "turn", "run", "context_id") if ex.get(k))
            out.append(f"- Evidence ({where}): {ex.get('evidence', '')}")
    _atomic_write(target_md, "\n".join(out) + "\n")


def get_open_mods_count(mods_json: Optional[Path] = None) -> int:
    mods = load_mods(mods_json)
    return sum(1 for m in mods.values() if isinstance(m, dict) and m.get("status") == "open")
